### ISSUE TITLE
Remove user/trainer/developer

### ISSUE THREAD

**Issue by za** [id-python/members#1]
We won't use this classification. Just 'member'.

**Comment by akbargumbira** [comment]
Hi, should we also keep email updates option?

**Comment by za** [comment]
@akbargumbira yes. It also will be required for forgot password feature.

**Comment by akbargumbira** [comment]
@za: when users register to the site, they don't make any password. Should the users want to edit/remove their data, there is a specific URL for each user to do so. That link will be sent after registration or they can use a 'forgot link' feature.
