### ISSUE TITLE
Provide a new favicon and marker

### ISSUE THREAD

**Issue by akbargumbira** [id-python/members#7]
@za: We need to put all the new configurations here:
https://github.com/akbargumbira/flask_user_map/blob/members.python.or.id/users/config.py.prod

**Comment by akbargumbira** [comment]
hi @iromli.. could you provide some python ID icons for this? Thanks

**Comment by iromli** [comment]
Which icon? the favicon or the marker one?

**Comment by iromli** [comment]
oh wait, there's artwork in https://github.com/id-python/direktori/tree/master/logo, i can convert it to `.png`
