### ISSUE TITLE
Provide a new mail configuration

### ISSUE THREAD

**Issue by akbargumbira** [id-python/members#8]
@za: We need to put all this configuration here. Currently it only supports using SMTP, but there is a branch on upstream to support sendmail.
https://github.com/akbargumbira/flask_user_map/blob/members.python.or.id/users/config.py.prod

**Comment by iromli** [comment]
@akbargumbira did you mean we use flask-sendmail instead of flask-mail?

**Comment by akbargumbira** [comment]
No, I prefer using flask-mail

**Comment by iromli** [comment]
@akbargumbira I see. I guess postfix is enough then?

@za do we have members@python.or.id address or something similar?

**Comment by za** [comment]
@iromli not yet, hence I don't know how to create a email alias at google hosted mail.

Do you know it?

**Comment by iromli** [comment]
@za sorry for late reply, perhaps this google search helps https://www.google.com/search?btnG=1&pws=0&q=google+apps+group+to+send+email&gws_rd=ssl

**Comment by iromli** [comment]
@za i think you'll need to create a separate account e.g. komunitas[at]python[dot]or[dot]id (and optionally set an alias for it) so it won't compromise your default address, since the credentials will be exposed in `config.py`

**Comment by iromli** [comment]
Our generous sponsor gives us free SMTP server; it's has been tested and worked like a charm — the email might arrived into spam folder
